"use client"

import { useState, useEffect } from "react"
import { motion, AnimatePresence } from "framer-motion"
import Link from "next/link"
import {
  ArrowLeft,
  Search,
  Filter,
  CheckCircle2,
  Clock,
  AlertTriangle,
  BarChart4,
  MapPin,
  Calendar,
  RefreshCw,
  ChevronDown,
  ChevronUp,
  MessageSquare,
  CloudRain,
  TrendingUp,
  AlertCircle,
  FileSpreadsheet,
  Layers,
  Upload,
} from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Input } from "@/components/ui/input"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"
import { Progress } from "@/components/ui/progress"
import { Textarea } from "@/components/ui/textarea"
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip"
import { Checkbox } from "@/components/ui/checkbox"

// Mock data for reported issues with Chennai locations
const MOCK_ISSUES = [
  {
    id: 1,
    title: "Pothole on Anna Salai",
    description:
      "Large pothole near the intersection of Anna Salai and Mount Road that poses a hazard to vehicles and cyclists.",
    category: "Roads",
    location: "Anna Salai, Chennai",
    status: "in-progress",
    priority: "high",
    date: "2023-11-15",
    reporter: "Raj Kumar",
    contact: "raj@example.com",
    assignedTo: "Roads Department",
    updates: [
      { date: "2023-11-16", note: "Issue received and assigned to Roads Department" },
      { date: "2023-11-18", note: "Scheduled for repair next week" },
    ],
    coordinates: { lat: 13.0569, lng: 80.2425 },
    predicted: false,
  },
  {
    id: 2,
    title: "Streetlight not working",
    description: "Streetlight has been out for 3 days, creating a safety concern for pedestrians at night.",
    category: "Utilities",
    location: "T. Nagar, Chennai",
    status: "pending",
    priority: "medium",
    date: "2023-11-17",
    reporter: "Priya Sharma",
    contact: "priya@example.com",
    assignedTo: "Unassigned",
    updates: [{ date: "2023-11-17", note: "Issue received and under review" }],
    coordinates: { lat: 13.0418, lng: 80.2341 },
    predicted: false,
  },
  {
    id: 3,
    title: "Fallen tree blocking sidewalk",
    description: "Tree fell during last night's storm and is completely blocking the pedestrian walkway.",
    category: "Parks",
    location: "Adyar, Chennai",
    status: "resolved",
    priority: "high",
    date: "2023-11-10",
    reporter: "Vikram Singh",
    contact: "vikram@example.com",
    assignedTo: "Parks Department",
    updates: [
      { date: "2023-11-10", note: "Issue received and assigned to Parks Department" },
      { date: "2023-11-11", note: "Crew dispatched to remove tree" },
      { date: "2023-11-12", note: "Tree removed and sidewalk cleared" },
    ],
    coordinates: { lat: 13.0012, lng: 80.2565 },
    predicted: false,
  },
  {
    id: 4,
    title: "Graffiti on public building",
    description: "Inappropriate graffiti on the west wall of the community center needs to be removed.",
    category: "Maintenance",
    location: "Mylapore, Chennai",
    status: "in-progress",
    priority: "low",
    date: "2023-11-14",
    reporter: "Anita Desai",
    contact: "anita@example.com",
    assignedTo: "Maintenance Department",
    updates: [
      { date: "2023-11-14", note: "Issue received and assigned to Maintenance Department" },
      { date: "2023-11-16", note: "Cleanup scheduled for next week" },
    ],
    coordinates: { lat: 13.0368, lng: 80.2676 },
    predicted: false,
  },
  {
    id: 5,
    title: "Broken playground equipment",
    description: "The swing set at Marina Beach Park has a broken chain that could be dangerous for children.",
    category: "Parks",
    location: "Marina Beach, Chennai",
    status: "pending",
    priority: "high",
    date: "2023-11-18",
    reporter: "Karthik Rajan",
    contact: "karthik@example.com",
    assignedTo: "Unassigned",
    updates: [{ date: "2023-11-18", note: "Issue received and under review" }],
    coordinates: { lat: 13.0500, lng: 80.2824 },
    predicted: false,
  },
]

// Mock data for predicted issues
const MOCK_PREDICTED_ISSUES = [
  {
    id: 101,
    title: "Potential flooding at T. Nagar",
    description: "Based on weather forecast and historical data, this area is at high risk of flooding during the upcoming monsoon season (December). Preventive drainage clearance recommended.",
    category: "Drainage",
    location: "T. Nagar, Chennai",
    status: "pending",
    priority: "high",
    date: "2023-11-19",
    reporter: "Predictive System",
    contact: "system@chennai.gov.in",
    assignedTo: "Unassigned",
    updates: [{ date: "2023-11-19", note: "Automatically generated by predictive system" }],
    coordinates: { lat: 13.0418, lng: 80.2341 },
    predicted: true,
    confidence: 87,
    preventiveMeasures: [
      "Clear drainage systems before monsoon arrives",
      "Install temporary flood barriers at key junctions",
      "Notify residents in low-lying areas"
    ],
    predictedDate: "2023-12-15",
    dataSource: ["Historical flooding data", "Weather forecast", "Topographical analysis"]
  },
  {
    id: 102,
    title: "Road deterioration likely on Poonamallee High Road",
    description: "Traffic analysis and road condition monitoring indicate this stretch will likely develop serious potholes within 1-2 months due to heavy vehicle traffic combined with upcoming rainfall.",
    category: "Roads",
    location: "Poonamallee High Road, Chennai",
    status: "pending",
    priority: "medium",
    date: "2023-11-19",
    reporter: "Predictive System",
    contact: "system@chennai.gov.in",
    assignedTo: "Unassigned",
    updates: [{ date: "2023-11-19", note: "Automatically generated by predictive system" }],
    coordinates: { lat: 13.0819, lng: 80.2110 },
    predicted: true,
    confidence: 75,
    preventiveMeasures: [
      "Schedule preemptive road resurfacing",
      "Implement temporary load restrictions for heavy vehicles",
      "Install warning signs for drivers"
    ],
    predictedDate: "2023-12-30",
    dataSource: ["Road condition sensors", "Traffic volume data", "Maintenance history"]
  },
  {
    id: 103,
    title: "Likely power outage in Velachery",
    description: "Analysis of power grid load patterns and equipment age indicates high probability of power failures in this area during peak summer demand.",
    category: "Utilities",
    location: "Velachery, Chennai",
    status: "pending",
    priority: "high",
    date: "2023-11-19",
    reporter: "Predictive System",
    contact: "system@chennai.gov.in",
    assignedTo: "Unassigned",
    updates: [{ date: "2023-11-19", note: "Automatically generated by predictive system" }],
    coordinates: { lat: 12.9815, lng: 80.2180 },
    predicted: true,
    confidence: 82,
    preventiveMeasures: [
      "Perform preventive maintenance on transformers",
      "Install backup generators at critical facilities",
      "Prepare load shedding schedule if necessary"
    ],
    predictedDate: "2024-04-15",
    dataSource: ["Power grid monitoring", "Equipment maintenance records", "Seasonal demand patterns"]
  },
  {
    id: 104,
    title: "Potential water shortage in Adyar",
    description: "Water reservoir levels and consumption trends indicate likely water shortage in this area during summer months.",
    category: "Water Supply",
    location: "Adyar, Chennai",
    status: "pending",
    priority: "medium",
    date: "2023-11-19",
    reporter: "Predictive System",
    contact: "system@chennai.gov.in",
    assignedTo: "Unassigned",
    updates: [{ date: "2023-11-19", note: "Automatically generated by predictive system" }],
    coordinates: { lat: 13.0012, lng: 80.2565 },
    predicted: true,
    confidence: 68,
    preventiveMeasures: [
      "Implement water conservation awareness campaign",
      "Schedule additional water tanker services",
      "Inspect and repair water distribution infrastructure"
    ],
    predictedDate: "2024-03-01",
    dataSource: ["Reservoir level data", "Consumption patterns", "Rainfall forecast"]
  },
  {
    id: 105,
    title: "Traffic congestion increase expected near Central Station",
    description: "Urban traffic patterns, upcoming events, and construction schedules indicate severe congestion in this area within the next month.",
    category: "Traffic",
    location: "Chennai Central Station Area",
    status: "pending",
    priority: "low",
    date: "2023-11-19",
    reporter: "Predictive System",
    contact: "system@chennai.gov.in",
    assignedTo: "Unassigned",
    updates: [{ date: "2023-11-19", note: "Automatically generated by predictive system" }],
    coordinates: { lat: 13.0836, lng: 80.2750 },
    predicted: true,
    confidence: 71,
    preventiveMeasures: [
      "Deploy additional traffic police during peak hours",
      "Adjust signal timing to optimize flow",
      "Recommend alternate routes through public advisory"
    ],
    predictedDate: "2023-12-10",
    dataSource: ["Traffic camera data", "Event calendar", "Construction schedules"]
  }
]

// Mock data for automated department assignments
const DEPARTMENT_MAPPING = {
  "Roads": "Roads and Highways Department",
  "Drainage": "Water and Drainage Department",
  "Utilities": "Metropolitan Utilities Board",
  "Parks": "Parks and Recreation Department",
  "Maintenance": "Public Works Maintenance Division",
  "Water Supply": "Chennai Metro Water Supply",
  "Traffic": "Traffic Management Department",
  "Public Facilities": "Public Facilities Management",
  "Waste Management": "Waste Management Authority",
  "Public Health": "Public Health Department"
}

// Mock weather data
const WEATHER_DATA = {
  forecast: [
    { date: "2023-11-20", condition: "Sunny", temperature: 30, precipitation: 0 },
    { date: "2023-11-21", condition: "Partly Cloudy", temperature: 29, precipitation: 10 },
    { date: "2023-11-22", condition: "Cloudy", temperature: 28, precipitation: 20 },
    { date: "2023-11-23", condition: "Light Rain", temperature: 27, precipitation: 40 },
    { date: "2023-11-24", condition: "Heavy Rain", temperature: 26, precipitation: 80 },
    { date: "2023-11-25", condition: "Thunderstorms", temperature: 25, precipitation: 90 },
    { date: "2023-11-26", condition: "Light Rain", temperature: 27, precipitation: 50 },
  ],
  alerts: [
    {
      type: "Heavy Rainfall",
      description: "Heavy rainfall expected on Nov 24-25, which may cause localized flooding in low-lying areas.",
      severity: "moderate",
      affectedAreas: ["T. Nagar", "Velachery", "Adyar"]
    }
  ],
  seasonalOutlook: "Monsoon season expected to begin in early December with above-average rainfall predicted."
}

// Mock historical issue patterns
const HISTORICAL_PATTERNS = [
  { category: "Roads", season: "Monsoon", frequency: "High", description: "Road damage increases by 40% during monsoon months" },
  { category: "Drainage", season: "Monsoon", frequency: "Very High", description: "Drainage issues peak in December-January" },
  { category: "Utilities", season: "Summer", frequency: "High", description: "Power outages increase by 30% during peak summer" },
  { category: "Water Supply", season: "Summer", frequency: "Very High", description: "Water shortage complaints rise by 60% in March-May" },
  { category: "Parks", season: "Storm", frequency: "Medium", description: "Tree falls most common during cyclone season" }
]

export default function GovernmentPage() {
  const [issues, setIssues] = useState([])
  const [activeTab, setActiveTab] = useState("all")
  const [searchQuery, setSearchQuery] = useState("")
  const [categoryFilter, setCategoryFilter] = useState("all")
  const [priorityFilter, setPriorityFilter] = useState("all")
  const [expandedIssue, setExpandedIssue] = useState(null)
  const [isRefreshing, setIsRefreshing] = useState(false)
  const [statusUpdates, setStatusUpdates] = useState({})
  const [mounted, setMounted] = useState(false)
  const [commentText, setCommentText] = useState({})
  const [viewMode, setViewMode] = useState("issues")
  const [includePredicted, setIncludePredicted] = useState(true)
  const [weatherAlerts, setWeatherAlerts] = useState(WEATHER_DATA.alerts)
  const [heatmapData, setHeatmapData] = useState([])
  const [showHeatmapControls, setShowHeatmapControls] = useState(false)
  const [heatmapFilter, setHeatmapFilter] = useState("all")

  useEffect(() => {
    setMounted(true)

    // Combine mock issues with predicted issues if included
    const allIssues = [...MOCK_ISSUES]
    if (includePredicted) {
      allIssues.push(...MOCK_PREDICTED_ISSUES)
    }

    // Try to load user-reported issues from localStorage
    try {
      const userReportedIssues = JSON.parse(localStorage.getItem("reportedIssues") || "[]")

      // Convert user-reported issues to the format expected by the government dashboard
      const formattedUserIssues = userReportedIssues.map((issue) => ({
        id: issue.id,
        title: issue.title,
        description: issue.description,
        category: issue.category,
        location: issue.location,
        status: issue.status || "pending",
        priority: issue.priority || "medium",
        date: issue.date,
        reporter: issue.reporter || "Anonymous",
        contact: issue.contact || "Not provided",
        assignedTo: DEPARTMENT_MAPPING[issue.category] || "Unassigned",
        updates: issue.updates || [
          { date: new Date().toISOString().split("T")[0], note: "Issue reported and pending review" },
        ],
        coordinates: issue.coordinates || { lat: 13.0500, lng: 80.2500 }, // Default to Chennai center
        predicted: false,
      }))

      // Combine with mock issues
      setIssues([...allIssues, ...formattedUserIssues])
    } catch (error) {
      console.error("Error loading user-reported issues:", error)
      setIssues(allIssues)
    }

    // Generate heatmap data
    generateHeatmapData()
  }, [includePredicted])

  const generateHeatmapData = () => {
    // Real implementation would calculate density based on actual coordinates
    // This is a simplified mock implementation
    const categoryColors = {
      "Roads": "#FF5733",
      "Drainage": "#3498DB",
      "Utilities": "#F1C40F",
      "Parks": "#2ECC71",
      "Maintenance": "#9B59B6",
      "Water Supply": "#3498DB",
      "Traffic": "#E74C3C",
      "Public Facilities": "#34495E",
    }

    const heatmapPoints = [
      // Anna Salai area
      { lat: 13.0569, lng: 80.2425, weight: 8, category: "Roads" },
      { lat: 13.0585, lng: 80.2410, weight: 5, category: "Roads" },
      { lat: 13.0550, lng: 80.2440, weight: 7, category: "Roads" },
      
      // T. Nagar area
      { lat: 13.0418, lng: 80.2341, weight: 9, category: "Drainage" },
      { lat: 13.0430, lng: 80.2330, weight: 6, category: "Drainage" },
      { lat: 13.0410, lng: 80.2350, weight: 8, category: "Utilities" },
      
      // Adyar area
      { lat: 13.0012, lng: 80.2565, weight: 4, category: "Parks" },
      { lat: 13.0020, lng: 80.2550, weight: 3, category: "Water Supply" },
      { lat: 13.0000, lng: 80.2580, weight: 5, category: "Parks" },
      
      // Mylapore area
      { lat: 13.0368, lng: 80.2676, weight: 2, category: "Maintenance" },
      { lat: 13.0380, lng: 80.2660, weight: 3, category: "Maintenance" },
      
      // Marina Beach area
      { lat: 13.0500, lng: 80.2824, weight: 7, category: "Parks" },
      { lat: 13.0520, lng: 80.2800, weight: 5, category: "Public Facilities" },
      
      // Central Station area
      { lat: 13.0836, lng: 80.2750, weight: 6, category: "Traffic" },
      { lat: 13.0850, lng: 80.2730, weight: 8, category: "Traffic" },
    ]

    setHeatmapData(heatmapPoints.map(point => ({
      ...point,
      color: categoryColors[point.category] || "#777777"
    })))
  }

  const refreshData = () => {
    setIsRefreshing(true)

    // Try to reload user-reported issues
    try {
      const userReportedIssues = JSON.parse(localStorage.getItem("reportedIssues") || "[]")

      const formattedUserIssues = userReportedIssues.map((issue) => ({
        id: issue.id,
        title: issue.title,
        description: issue.description,
        category: issue.category,
        location: issue.location,
        status: issue.status || "pending",
        priority: issue.priority || "medium",
        date: issue.date,
        reporter: issue.reporter || "Anonymous",
        contact: issue.contact || "Not provided",
        assignedTo: DEPARTMENT_MAPPING[issue.category] || "Unassigned",
        updates: issue.updates || [
          { date: new Date().toISOString().split("T")[0], note: "Issue reported and pending review" },
        ],
        coordinates: issue.coordinates || { lat: 13.0500, lng: 80.2500 }, // Default to Chennai center
        predicted: false,
      }))

      // Combine with mock issues and predicted issues if included
      const baseIssues = [...MOCK_ISSUES]
      if (includePredicted) {
        baseIssues.push(...MOCK_PREDICTED_ISSUES)
      }
      
      setIssues([...baseIssues, ...formattedUserIssues])
    } catch (error) {
      console.error("Error reloading user-reported issues:", error)
      
      // Fall back to mock data
      const baseIssues = [...MOCK_ISSUES]
      if (includePredicted) {
        baseIssues.push(...MOCK_PREDICTED_ISSUES)
      }
      setIssues(baseIssues)
    }

    // Refresh heatmap data
    generateHeatmapData()

    setTimeout(() => {
      setIsRefreshing(false)
    }, 1500)
  }

  const toggleExpand = (id) => {
    setExpandedIssue(expandedIssue === id ? null : id)
  }

  const updateIssueStatus = (id, newStatus) => {
    const updatedIssues = issues.map((issue) => {
      if (issue.id === id) {
        // Add status update
        const statusText =
          newStatus === "resolved"
            ? "Issue marked as resolved"
            : newStatus === "in-progress"
              ? "Issue marked as in progress"
              : "Issue marked as pending"

        const updatedIssue = {
          ...issue,
          status: newStatus,
          updates: [...issue.updates, { date: new Date().toISOString().split("T")[0], note: statusText }],
        }

        return updatedIssue
      }
      return issue
    })

    setIssues(updatedIssues)

    // Update localStorage if this is a user-reported issue
    try {
      const userReportedIssues = JSON.parse(localStorage.getItem("reportedIssues") || "[]")
      const updatedUserIssues = userReportedIssues.map((issue) => {
        if (issue.id === id) {
          return {
            ...issue,
            status: newStatus,
            updates: [
              ...(issue.updates || []),
              {
                date: new Date().toISOString().split("T")[0],
                note:
                  newStatus === "resolved"
                    ? "Issue marked as resolved"
                    : newStatus === "in-progress"
                      ? "Issue marked as in progress"
                      : "Issue marked as pending",
              },
            ],
          }
        }
        return issue
      })

      localStorage.setItem("reportedIssues", JSON.stringify(updatedUserIssues))
    } catch (error) {
      console.error("Error updating user-reported issues:", error)
    }

    // Show temporary status update message
    setStatusUpdates({
      ...statusUpdates,
      [id]: { message: `Status updated to ${newStatus}`, timestamp: Date.now() },
    })

    // Clear status update message after 3 seconds
    setTimeout(() => {
      setStatusUpdates((prev) => {
        const newUpdates = { ...prev }
        delete newUpdates[id]
        return newUpdates
      })
    }, 3000)
  }

  const assignToDepartment = (id, department) => {
    const updatedIssues = issues.map((issue) => {
      if (issue.id === id) {
        return {
          ...issue,
          assignedTo: department,
          updates: [...issue.updates, 
            { date: new Date().toISOString().split("T")[0], note: `Issue assigned to ${department}` }
          ],
        }
      }
      return issue
    })

    setIssues(updatedIssues)

    // Show temporary status update message
    setStatusUpdates({
      ...statusUpdates,
      [id]: { message: `Assigned to ${department}`, timestamp: Date.now() },
    })

    // Clear status update message after 3 seconds
    setTimeout(() => {
      setStatusUpdates((prev) => {
        const newUpdates = { ...prev }
        delete newUpdates[id]
        return newUpdates
      })
    }, 3000)
  }

  const handleCommentChange = (id, text) => {
    setCommentText({
      ...commentText,
      [id]: text,
    })
  }

  const addComment = (id) => {
    if (!commentText[id] || commentText[id].trim() === "") return

    const updatedIssues = issues.map((issue) => {
      if (issue.id === id) {
        return {
          ...issue,
          updates: [
            ...issue.updates,
            {
              date: new Date().toISOString().split("T")[0],
              note: commentText[id],
            },
          ],
        }
      }
      return issue
    })

    setIssues(updatedIssues)

    // Update localStorage if this is a user-reported issue
    try {
      const userReportedIssues = JSON.parse(localStorage.getItem("reportedIssues") || "[]")
      const updatedUserIssues = userReportedIssues.map((issue) => {
        if (issue.id === id) {
          return {
            ...issue,
            updates: [
              ...(issue.updates || []),
              {
                date: new Date().toISOString().split("T")[0],
                note: commentText[id],
              },
            ],
          }
        }
        return issue
      })

      localStorage.setItem("reportedIssues", JSON.stringify(updatedUserIssues))
    } catch (error) {
      console.error("Error updating user-reported issues:", error)
    }

    // Clear the comment text
    setCommentText({
      ...commentText,
      [id]: "",
    })

    // Show temporary status update message
    setStatusUpdates({
      ...statusUpdates,
      [id]: { message: `Comment added successfully`, timestamp: Date.now() },
    })

    // Clear status update message after 3 seconds
    setTimeout(() => {
      setStatusUpdates((prev) => {
        const newUpdates = { ...prev }
        delete newUpdates[id]
        return newUpdates
      })
    }, 3000)
  }

  const implementPreventiveMeasure = (issueId, measures) => {
    const updatedIssues = issues.map((issue) => {
      if (issue.id === issueId) {
        return {
          ...issue,
          status: "in-progress",
          updates: [...issue.updates, 
            { 
              date: new Date().toISOString().split("T")[0], 
              note: `Preventive measures initiated: ${measures.join(', ')}` 
            }
          ],
        }
      }
      return issue
    })

    setIssues(updatedIssues)

    // Show temporary status update message
    setStatusUpdates({
      ...statusUpdates,
      [issueId]: { message: `Preventive measures initiated`, timestamp: Date.now() },
    })

    // Clear status update message after 3 seconds
    setTimeout(() => {
      setStatusUpdates((prev) => {
        const newUpdates = { ...prev }
        delete newUpdates[issueId]
        return newUpdates
      })
    }, 3000)
  }

  const getStatusIcon = (status) => {
    switch (status) {
      case "resolved":
        return <CheckCircle2 className="h-5 w-5 text-green-500" />
      case "in-progress":
        return <Clock className="h-5 w-5 text-blue-500" />
      default:
        return <AlertTriangle className="h-5 w-5 text-amber-500" />
    }
  }

  const getStatusText = (status) => {
    switch (status) {
      case "resolved":
        return "Resolved"
      case "in-progress":
        return "In Progress"
      default:
        return "Pending"
    }
  }

  const getStatusColor = (status) => {
    switch (status) {
      case "resolved":
        return "bg-green-100 text-green-800 border-green-300"
      case "in-progress":
        return "bg-blue-100 text-blue-800 border-blue-300"
      default:
        return "bg-amber-100 text-amber-800 border-amber-300"
    }
  }

  const getPriorityColor = (priority) => {
    switch (priority) {
      case "high":
        return "bg-rose-100 text-rose-800 border-rose-300"
      case "medium":
        return "bg-amber-100 text-amber-800 border-amber-300"
      default:
        return "bg-emerald-100 text-emerald-800 border-emerald-300"
    }
  }

  const filteredIssues = issues.filter((issue) => {
    // Filter by status tab
    if (activeTab !== "all" && issue.status !== activeTab) return false

    // Filter by search query
    if (
      searchQuery &&
      !issue.title.toLowerCase().includes(searchQuery.toLowerCase()) &&
      !issue.description.toLowerCase().includes(searchQuery.toLowerCase()) &&
      !issue.location.toLowerCase().includes(searchQuery.toLowerCase())
    )
      return false

    // Filter by category
    if (categoryFilter !== "all" && issue.category.toLowerCase() !== categoryFilter.toLowerCase()) return false

    // Filter by priority
    if (priorityFilter !== "all" && issue.priority !== priorityFilter) return false

    return true
  })

  // Calculate statistics
  const totalIssues = issues.length
  const pendingIssues = issues.filter((i) => i.status === "pending").length
  const inProgressIssues = issues.filter((i) => i.status === "in-progress").length
  const resolvedIssues = issues.filter((i) => i.status === "resolved").length

  const highPriorityIssues = issues.filter((i) => i.priority === "high").length
  const mediumPriorityIssues = issues.filter((i) => i.priority === "medium").length
  const lowPriorityIssues = issues.filter((i) => i.priority === "low").length

  const predictedIssues = issues.filter((i) => i.predicted).length
  const reportedIssues = issues.filter((i) => !i.predicted).length

  // Weather-related issues count
  const weatherRelatedIssues = issues.filter(
    i => i.category === "Drainage" || 
         i.description.toLowerCase().includes("flood") || 
         i.description.toLowerCase().includes("rain") ||
         i.description.toLowerCase().includes("water")
  ).length

  if (!mounted) return null

  return (
    <div className="min-h-screen bg-gradient-to-br from-[#f7f9fb] to-[#edf2f7]">
      <div className="container mx-auto p-4">
        <header className="flex items-center justify-between mb-8">
          <div className="flex items-center gap-3">
            <Link href="/" className="flex items-center gap-2">
              <ArrowLeft className="h-5 w-5" />
              <span className="font-medium">Back to Home</span>
            </Link>
            
          </div>
          <TooltipProvider>
            <Tooltip>
              <TooltipTrigger asChild>
                <Button
                  variant="outline"
                  size="icon"
                  className="ml-2"
                  onClick={refreshData}
                  disabled={isRefreshing}
                >
                  <RefreshCw className={`h-5 w-5 ${isRefreshing ? "animate-spin" : ""}`} />
                </Button>
              </TooltipTrigger>
              <TooltipContent>
                <p>Refresh data</p>
              </TooltipContent>
            </Tooltip>
          </TooltipProvider>
        </header>

        <Tabs value={viewMode} onValueChange={setViewMode} className="mb-8">
          <TabsList className="grid w-full max-w-md grid-cols-3">
            <TabsTrigger value="issues">Issue Management</TabsTrigger>
            <TabsTrigger value="analytics">Analytics</TabsTrigger>
            <TabsTrigger value="weather">Weather Alert</TabsTrigger>
          </TabsList>
        </Tabs>

        {viewMode === "issues" && (
          <>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
              <Card>
                <CardHeader className="pb-2">
                  <CardTitle className="text-sm font-medium text-gray-500">Total Issues</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="text-3xl font-bold">{totalIssues}</div>
                  <div className="flex justify-between mt-2">
                    <div className="text-sm text-gray-500">Reported: {reportedIssues}</div>
                    <div className="text-sm text-gray-500">Predicted: {predictedIssues}</div>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader className="pb-2">
                  <CardTitle className="text-sm font-medium text-gray-500">Issue Status</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="flex justify-between mb-2">
                    <div className="text-sm">Pending</div>
                    <div className="text-sm font-semibold">{pendingIssues}</div>
                  </div>
                  <Progress value={(pendingIssues / totalIssues) * 100} className="h-2 bg-amber-100" />
                  <div className="flex justify-between mb-2 mt-4">
                    <div className="text-sm">In Progress</div>
                    <div className="text-sm font-semibold">{inProgressIssues}</div>
                  </div>
                  <Progress value={(inProgressIssues / totalIssues) * 100} className="h-2 bg-blue-100" />
                  <div className="flex justify-between mb-2 mt-4">
                    <div className="text-sm">Resolved</div>
                    <div className="text-sm font-semibold">{resolvedIssues}</div>
                  </div>
                  <Progress value={(resolvedIssues / totalIssues) * 100} className="h-2 bg-green-100" />
                </CardContent>
              </Card>
              <Card>
                <CardHeader className="pb-2">
                  <CardTitle className="text-sm font-medium text-gray-500">Priority Distribution</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="flex justify-between mb-2">
                    <div className="text-sm">High</div>
                    <div className="text-sm font-semibold">{highPriorityIssues}</div>
                  </div>
                  <Progress value={(highPriorityIssues / totalIssues) * 100} className="h-2 bg-rose-100" />
                  <div className="flex justify-between mb-2 mt-4">
                    <div className="text-sm">Medium</div>
                    <div className="text-sm font-semibold">{mediumPriorityIssues}</div>
                  </div>
                  <Progress value={(mediumPriorityIssues / totalIssues) * 100} className="h-2 bg-amber-100" />
                  <div className="flex justify-between mb-2 mt-4">
                    <div className="text-sm">Low</div>
                    <div className="text-sm font-semibold">{lowPriorityIssues}</div>
                  </div>
                  <Progress value={(lowPriorityIssues / totalIssues) * 100} className="h-2 bg-emerald-100" />
                </CardContent>
              </Card>
              <Card>
                <CardHeader className="pb-2">
                  <CardTitle className="text-sm font-medium text-gray-500">Weather Impact</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="text-3xl font-bold">{weatherRelatedIssues}</div>
                  <div className="text-sm text-gray-500 mt-2">Weather-related issues</div>
                  {weatherAlerts.length > 0 && (
                    <div className="flex items-center gap-2 mt-4">
                      <CloudRain className="h-5 w-5 text-blue-500" />
                      <div className="text-sm text-blue-700 font-medium">Active weather alerts: {weatherAlerts.length}</div>
                    </div>
                  )}
                </CardContent>
              </Card>
            </div>

            <div className="flex flex-col lg:flex-row gap-4 mb-6">
              <div className="flex-grow flex flex-col sm:flex-row gap-2">
                <div className="relative flex-grow">
                  <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-gray-500" />
                  <Input
                    type="text"
                    placeholder="Search issues..."
                    className="pl-8"
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                  />
                </div>
                <div className="flex gap-2">
                  <Select value={categoryFilter} onValueChange={setCategoryFilter}>
                    <SelectTrigger className="w-[140px]">
                      <SelectValue placeholder="Category" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="all">All Categories</SelectItem>
                      <SelectItem value="roads">Roads</SelectItem>
                      <SelectItem value="utilities">Utilities</SelectItem>
                      <SelectItem value="parks">Parks</SelectItem>
                      <SelectItem value="maintenance">Maintenance</SelectItem>
                      <SelectItem value="drainage">Drainage</SelectItem>
                      <SelectItem value="water supply">Water Supply</SelectItem>
                      <SelectItem value="traffic">Traffic</SelectItem>
                    </SelectContent>
                  </Select>
                  <Select value={priorityFilter} onValueChange={setPriorityFilter}>
                    <SelectTrigger className="w-[140px]">
                      <SelectValue placeholder="Priority" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="all">All Priorities</SelectItem>
                      <SelectItem value="high">High</SelectItem>
                      <SelectItem value="medium">Medium</SelectItem>
                      <SelectItem value="low">Low</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <Filter className="h-4 w-4 text-gray-500" />
                <span className="text-sm text-gray-700">Include predicted issues</span>
                <Checkbox
                  checked={includePredicted}
                  onCheckedChange={setIncludePredicted}
                  id="include-predicted"
                />
              </div>
            </div>

            <div className="mb-6">
              <Tabs defaultValue="all" value={activeTab} onValueChange={setActiveTab}>
                <TabsList>
                  <TabsTrigger value="all" className="relative">
                    All Issues
                    <Badge className="ml-2 px-1.5 h-5 text-xs">{issues.length}</Badge>
                  </TabsTrigger>
                  <TabsTrigger value="pending" className="relative">
                    Pending
                    <Badge className="ml-2 px-1.5 h-5 text-xs">{pendingIssues}</Badge>
                  </TabsTrigger>
                  <TabsTrigger value="in-progress" className="relative">
                    In Progress
                    <Badge className="ml-2 px-1.5 h-5 text-xs">{inProgressIssues}</Badge>
                  </TabsTrigger>
                  <TabsTrigger value="resolved" className="relative">
                    Resolved
                    <Badge className="ml-2 px-1.5 h-5 text-xs">{resolvedIssues}</Badge>
                  </TabsTrigger>
                </TabsList>
              </Tabs>
            </div>

            <AnimatePresence>
              {filteredIssues.length === 0 ? (
                <div className="text-center py-12">
                  <p className="text-gray-500">No issues found matching your filters.</p>
                </div>
              ) : (
                <div className="space-y-4">
                  {filteredIssues.map((issue) => (
                    <motion.div
                      key={issue.id}
                      initial={{ opacity: 0, y: 20 }}
                      animate={{ opacity: 1, y: 0 }}
                      exit={{ opacity: 0, y: -20 }}
                      transition={{ duration: 0.2 }}
                    >
                      <Card className={issue.predicted ? "border-l-4 border-l-indigo-400" : ""}>
                        <CardHeader className="pb-2">
                          <div className="flex justify-between items-start">
                            <div className="flex-1">
                              <div className="flex items-center gap-2">
                                <CardTitle className="text-lg font-semibold">{issue.title}</CardTitle>
                                {issue.predicted && (
                                  <Badge variant="outline" className="bg-indigo-100 text-indigo-800 border-indigo-300">
                                    Predicted
                                  </Badge>
                                )}
                              </div>
                              <div className="flex flex-wrap gap-2 mt-2">
                                <Badge variant="outline" className={getStatusColor(issue.status)}>
                                  <div className="flex items-center gap-1">
                                    {getStatusIcon(issue.status)}
                                    {getStatusText(issue.status)}
                                  </div>
                                </Badge>
                                <Badge variant="outline" className={getPriorityColor(issue.priority)}>
                                  {issue.priority.charAt(0).toUpperCase() + issue.priority.slice(1)} Priority
                                </Badge>
                                <Badge variant="outline" className="bg-gray-100 text-gray-800 border-gray-300">
                                  {issue.category}
                                </Badge>
                                <Badge variant="outline" className="bg-gray-100 text-gray-800 border-gray-300">
                                  <div className="flex items-center gap-1">
                                    <MapPin className="h-3 w-3" />
                                    {issue.location}
                                  </div>
                                </Badge>
                                <Badge variant="outline" className="bg-gray-100 text-gray-800 border-gray-300">
                                  <div className="flex items-center gap-1">
                                    <Calendar className="h-3 w-3" />
                                    {issue.date}
                                  </div>
                                </Badge>
                              </div>
                            </div>
                            <Button
                              variant="ghost"
                              size="icon"
                              onClick={() => toggleExpand(issue.id)}
                              className="h-8 w-8"
                            >
                              {expandedIssue === issue.id ? (
                                <ChevronUp className="h-4 w-4" />
                              ) : (
                                <ChevronDown className="h-4 w-4" />
                              )}
                            </Button>
                          </div>
                        </CardHeader>
                        <CardContent className="pt-0">
                          <p className="text-sm text-gray-600">{issue.description}</p>
                          {expandedIssue === issue.id && (
                            <motion.div
                              initial={{ opacity: 0, height: 0 }}
                              animate={{ opacity: 1, height: "auto" }}
                              exit={{ opacity: 0, height: 0 }}
                              transition={{ duration: 0.2 }}
                              className="mt-4 space-y-4"
                            >
                              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                <div>
                                  <h4 className="text-sm font-semibold mb-2">Reported By</h4>
                                  <p className="text-sm">{issue.reporter}</p>
                                  {issue.contact && <p className="text-sm text-gray-500">{issue.contact}</p>}
                                </div>
                                <div>
                                  <h4 className="text-sm font-semibold mb-2">Assigned To</h4>
                                  <p className="text-sm">{issue.assignedTo || "Unassigned"}</p>
                                  {issue.assignedTo === "Unassigned" && (
                                    <Select
                                      onValueChange={(value) => assignToDepartment(issue.id, value)}
                                    >
                                      <SelectTrigger className="h-8 mt-1 text-xs">
                                        <SelectValue placeholder="Assign to department" />
                                      </SelectTrigger>
                                      <SelectContent>
                                        {Object.values(DEPARTMENT_MAPPING).map((dept) => (
                                          <SelectItem key={dept} value={dept}>
                                            {dept}
                                          </SelectItem>
                                        ))}
                                      </SelectContent>
                                    </Select>
                                  )}
                                </div>
                              </div>

                              {issue.predicted && (
                                <div>
                                  <div className="flex items-center gap-2 mb-2">
                                    <h4 className="text-sm font-semibold">Prediction Details</h4>
                                    <Badge className="bg-indigo-100 text-indigo-800 border-indigo-300">
                                      {issue.confidence}% Confidence
                                    </Badge>
                                  </div>
                                  <div className="space-y-2">
                                    <p className="text-sm">
                                      <span className="font-medium">Predicted Date:</span> {issue.predictedDate}
                                    </p>
                                    <div>
                                      <p className="text-sm font-medium mb-1">Recommended Preventive Measures:</p>
                                      <ul className="list-disc list-inside text-sm space-y-1">
                                        {issue.preventiveMeasures.map((measure, idx) => (
                                          <li key={idx}>{measure}</li>
                                        ))}
                                      </ul>
                                    </div>
                                    <div>
                                      <p className="text-sm font-medium mb-1">Data Sources:</p>
                                      <div className="flex flex-wrap gap-1">
                                        {issue.dataSource.map((source, idx) => (
                                          <Badge key={idx} variant="outline" className="text-xs">
                                            {source}
                                          </Badge>
                                        ))}
                                      </div>
                                    </div>
                                    <div className="pt-2">
                                      <Button 
                                        size="sm" 
                                        className="bg-indigo-600 hover:bg-indigo-700"
                                        onClick={() => implementPreventiveMeasure(issue.id, issue.preventiveMeasures)}
                                      >
                                        Implement Preventive Measures
                                      </Button>
                                    </div>
                                  </div>
                                </div>
                              )}

                              <div>
                                <h4 className="text-sm font-semibold mb-2">Updates & Notes</h4>
                                <div className="space-y-2 max-h-40 overflow-y-auto pr-2">
                                  {issue.updates.map((update, idx) => (
                                    <div key={idx} className="text-sm border-l-2 border-gray-200 pl-3 py-1">
                                      <p className="text-gray-500 text-xs">{update.date}</p>
                                      <p>{update.note}</p>
                                    </div>
                                  ))}
                                </div>
                                <div className="mt-3 space-y-2">
                                  <Textarea
                                    placeholder="Add a comment or update..."
                                    className="text-sm min-h-[80px]"
                                    value={commentText[issue.id] || ""}
                                    onChange={(e) => handleCommentChange(issue.id, e.target.value)}
                                  />
                                  <Button size="sm" onClick={() => addComment(issue.id)}>
                                    <MessageSquare className="h-4 w-4 mr-2" />
                                    Add Comment
                                  </Button>
                                </div>
                              </div>
                            </motion.div>
                          )}
                        </CardContent>
                        <CardFooter className="pt-0 flex justify-between">
                          <div className="flex gap-2">
                            {issue.status !== "resolved" && (
                              <Button
                                size="sm"
                                className="bg-green-600 hover:bg-green-700"
                                onClick={() => updateIssueStatus(issue.id, "resolved")}
                              >
                                <CheckCircle2 className="h-4 w-4 mr-2" />
                                Mark Resolved
                              </Button>
                            )}
                            {issue.status !== "in-progress" && issue.status !== "resolved" && (
                              <Button
                                size="sm"
                                className="bg-blue-600 hover:bg-blue-700"
                                onClick={() => updateIssueStatus(issue.id, "in-progress")}
                              >
                                <Clock className="h-4 w-4 mr-2" />
                                Mark In Progress
                              </Button>
                            )}
                            {issue.status !== "pending" && (
                              <Button
                                size="sm"
                                variant="outline"
                                onClick={() => updateIssueStatus(issue.id, "pending")}
                              >
                                Reset to Pending
                              </Button>
                            )}
                          </div>
                          {statusUpdates[issue.id] && (
                            <motion.div
                              initial={{ opacity: 0, x: 20 }}
                              animate={{ opacity: 1, x: 0 }}
                              exit={{ opacity: 0, x: 20 }}
                              className="text-sm text-green-600"
                            >
                              {statusUpdates[issue.id].message}
                            </motion.div>
                          )}
                        </CardFooter>
                      </Card>
                    </motion.div>
                  ))}
                </div>
              )}
            </AnimatePresence>
          </>
        )}

        {viewMode === "analytics" && (
          <div className="space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <BarChart4 className="h-5 w-5" />
                    Issue Categories Distribution
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-4">
                    {["Roads", "Utilities", "Parks", "Maintenance", "Drainage", "Water Supply", "Traffic"].map(
                      (category) => {
                        const count = issues.filter((i) => i.category === category).length
                        const percentage = (count / totalIssues) * 100
                        return (
                          <div key={category} className="space-y-1">
                            <div className="flex justify-between text-sm">
                              <span>{category}</span>
                              <span className="font-medium">{count} issues ({percentage.toFixed(1)}%)</span>
                            </div>
                            <Progress value={percentage} className="h-2" />
                          </div>
                        )
                      }
                    )}
                  </div>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <MapPin className="h-5 w-5" />
                    Geographic Distribution
                  </CardTitle>
                </CardHeader>
                <CardContent className="p-2">
                  <div className="relative h-[300px] bg-gray-100 rounded-md overflow-hidden flex items-center justify-center">
                    <div className="absolute top-2 right-2 z-10">
                      <Button 
                        variant="outline" 
                        size="sm" 
                        onClick={() => setShowHeatmapControls(!showHeatmapControls)}
                        className="bg-white"
                      >
                        <Layers className="h-4 w-4 mr-2" />
                        Heatmap Controls
                      </Button>
                      
                      {showHeatmapControls && (
                        <div className="mt-2 p-3 bg-white rounded-md shadow-md">
                          <h4 className="text-sm font-medium mb-2">Filter Heatmap</h4>
                          <Select value={heatmapFilter} onValueChange={setHeatmapFilter}>
                            <SelectTrigger className="w-full h-8 text-xs">
                              <SelectValue placeholder="Filter by category" />
                            </SelectTrigger>
                            <SelectContent>
                              <SelectItem value="all">All Categories</SelectItem>
                              <SelectItem value="Roads">Roads</SelectItem>
                              <SelectItem value="Drainage">Drainage</SelectItem>
                              <SelectItem value="Utilities">Utilities</SelectItem>
                              <SelectItem value="Parks">Parks</SelectItem>
                              <SelectItem value="Water Supply">Water Supply</SelectItem>
                              <SelectItem value="Traffic">Traffic</SelectItem>
                            </SelectContent>
                          </Select>
                        </div>
                      )}
                    </div>
                    
                    <div className="text-center">
                      <p>Chennai Heatmap View</p>
                      <p className="text-sm text-gray-500">(Displaying {heatmapFilter === 'all' ? 'all' : heatmapFilter} issue density)</p>
                    </div>
                  </div>
                </CardContent>
                <CardFooter>
                  <p className="text-sm text-gray-500">
                    The heatmap shows issue density across different areas of Chennai.
                  </p>
                </CardFooter>
              </Card>
            </div>
            
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <TrendingUp className="h-5 w-5" />
                  Historical Issue Patterns
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5 gap-4">
                    {HISTORICAL_PATTERNS.map((pattern, idx) => (
                      <Card key={idx} className="bg-gray-50">
                        <CardHeader className="pb-2">
                          <CardTitle className="text-sm">{pattern.category}</CardTitle>
                          <Badge variant="outline" className="bg-indigo-100 text-indigo-800 border-indigo-300">
                            {pattern.season} Season
                          </Badge>
                        </CardHeader>
                        <CardContent>
                          <Badge 
                            className={
                              pattern.frequency === "Very High" ? "bg-rose-100 text-rose-800 border-rose-300" :
                              pattern.frequency === "High" ? "bg-amber-100 text-amber-800 border-amber-300" :
                              "bg-emerald-100 text-emerald-800 border-emerald-300"
                            }
                          >
                            {pattern.frequency} Frequency
                          </Badge>
                          <p className="text-sm mt-2">{pattern.description}</p>
                        </CardContent>
                      </Card>
                    ))}
                  </div>
                </div>
              </CardContent>
              
            </Card>
          </div>
        )}

        {viewMode === "weather" && (
          <div className="space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <CloudRain className="h-5 w-5" />
                    Weather Forecast & Alerts
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-4">
                    <div className="grid grid-cols-7 gap-2">
                      {WEATHER_DATA.forecast.map((day, idx) => (
                        <div key={idx} className="text-center p-2 rounded-md bg-gray-50">
                          <p className="text-xs font-medium">{day.date.split('-')[2]}</p>
                          <div className="my-2">
                            {day.condition.includes("Rain") ? (
                              <CloudRain className="h-6 w-6 mx-auto text-blue-500" />
                            ) : day.condition.includes("Cloud") ? (
                              <div className="h-6 w-6 mx-auto bg-gray-300 rounded-full" />
                            ) : (
                              <div className="h-6 w-6 mx-auto bg-yellow-300 rounded-full" />
                            )}
                          </div>
                          <p className="text-sm font-bold">{day.temperature}°C</p>
                          <p className="text-xs">{day.precipitation}%</p>
                        </div>
                      ))}
                    </div>
                    
                    <div className="mt-6">
                      <h3 className="text-sm font-semibold mb-2">Weather Alerts</h3>
                      {WEATHER_DATA.alerts.map((alert, idx) => (
                        <div key={idx} className="bg-amber-50 border border-amber-200 rounded-md p-3 mb-3">
                          <div className="flex items-center gap-2">
                            <AlertCircle className="h-5 w-5 text-amber-500" />
                            <h4 className="font-medium">{alert.type}</h4>
                            <Badge 
                              className={
                                alert.severity === "high" ? "bg-rose-100 text-rose-800 border-rose-300" :
                                alert.severity === "moderate" ? "bg-amber-100 text-amber-800 border-amber-300" :
                                "bg-blue-100 text-blue-800 border-blue-300"
                              }
                            >
                              {alert.severity} severity
                            </Badge>
                          </div>
                          <p className="text-sm mt-2">{alert.description}</p>
                          <div className="mt-2">
                            <p className="text-xs font-medium">Affected Areas:</p>
                            <div className="flex flex-wrap gap-1 mt-1">
                              {alert.affectedAreas.map((area, areaIdx) => (
                                <Badge key={areaIdx} variant="outline" className="text-xs">
                                  {area}
                                </Badge>
                              ))}
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                </CardContent>
                <CardFooter>
                  <p className="text-sm text-gray-500">{WEATHER_DATA.seasonalOutlook}</p>
                </CardFooter>
              </Card>
              
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <FileSpreadsheet className="h-5 w-5" />
                    Weather-Related Issues
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-4">
                    <div className="border rounded-md overflow-hidden">
                      <table className="min-w-full divide-y divide-gray-200">
                        <thead className="bg-gray-50">
                          <tr>
                            <th className="px-3 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                              Issue
                            </th>
                            <th className="px-3 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                              Location
                            </th>
                            <th className="px-3 py-2 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                              Status
                            </th>
                          </tr>
                        </thead>
                        <tbody className="bg-white divide-y divide-gray-200">
                          {issues
                            .filter(
                              i => i.category === "Drainage" || 
                                  i.description.toLowerCase().includes("flood") || 
                                  i.description.toLowerCase().includes("rain") ||
                                  i.description.toLowerCase().includes("water")
                                )
                                .map((issue) => (
                                  <tr key={issue.id} className="hover:bg-gray-50">
                                    <td className="px-3 py-2 text-sm">
                                      <div className="font-medium">{issue.title}</div>
                                      <div className="text-xs text-gray-500">{issue.category}</div>
                                    </td>
                                    <td className="px-3 py-2 text-sm">
                                      <div className="flex items-center gap-1">
                                        <MapPin className="h-4 w-4 text-gray-500" />
                                        {issue.location}
                                      </div>
                                    </td>
                                    <td className="px-3 py-2 text-sm">
                                      <Badge variant="outline" className={getStatusColor(issue.status)}>
                                        {getStatusText(issue.status)}
                                      </Badge>
                                    </td>
                                  </tr>
                                ))}
                            </tbody>
                          </table>
                        </div>
                      </div>
                    </CardContent>
                    <CardFooter>
                      <p className="text-sm text-gray-500">
                        Showing {weatherRelatedIssues} weather-related issues.
                      </p>
                    </CardFooter>
                  </Card>
                </div>
              </div>
            )}
          </div>
        </div>
      )
    }